In [2]:
#pip install nump

In [8]:
#import numpy or pip install numpy

In [ ]:
import numpy as np
import pandas as pd
from numpy import random
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
type(arr1)

numpy.ndarray

In [1]:
print("srimadhi")

srimadhi


In [12]:
import numpy as np
a=np.array([[1,4,5],[34,64,5]])
a
type(a)


numpy.ndarray

In [ ]:
#dimensions of array
a1d=np.array([1,2,3,4,5,6])
a2d=np.array([[1,3,2,5,5],[2,6,7,4,6]])
a3d=np.array([[1,3,2,5,5],[2,6,7,4,6],[2,6,7,4,6]])
a4d=np.array([[1,3,2,5,5],[2,6,7,4,6],[2,6,7,4,6],[2,6,7,4,6]])


In [1]:
"madhi"

'madhi'

In [4]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr_reshap = arr1d.reshape((3, 4))

print(arr_reshap) 



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
import numpy as np
a=np.array([[1,4,5],[34,64,5]])
a

array([[ 1,  4,  5],
       [34, 64,  5]])

In [46]:
#indexing and slicing

In [40]:
import numpy as np
a1d=np.array([1,2,3,4,5,6])
a2d=np.array([[1,3,2,5,5],[2,6,7,4,6]])
a3d=np.array([[1,3,2,5,5],[2,6,7,4,6],[2,6,7,4,6]])
a4d=np.array([[1,3,2,5,5],[2,6,7,4,6],[2,6,7,4,6],[2,6,7,4,6]])
print("index",a2d[1,1])
print("slicing",a1d[1:4])
print(a2d)
print(a3d)
print(a4d)



index 6
slicing [2 3 4]
[[1 3 2 5 5]
 [2 6 7 4 6]]
[[1 3 2 5 5]
 [2 6 7 4 6]
 [2 6 7 4 6]]
[[1 3 2 5 5]
 [2 6 7 4 6]
 [2 6 7 4 6]
 [2 6 7 4 6]]


In [50]:
from numpy import random
a=random.randint(50)
a

18

In [3]:
import pandas as pd 
data = {"a":[1,2,3],"b":[2204,2023,2024]}
df=pd.DataFrame(data)
df

a     b
0  1  2204
1  2  2023
2  3  2024

In [5]:
import os
print(os.path.isfile('student_data.csv'))  # return True if the file exists


True


In [7]:
import pandas as pd

emp = pd.read_csv("student_data.csv")
df=pd.DataFrame(emp)
df

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        6   5   6   6  
1    ...      5        3      3     1     1      3        4   5   5   6  
2    ...      4        3      2     2     3      3       10   7   8  10  
3    ...      3        2      2     1     1      5        2  15  14  15  
4    ...      4        3      2     1     2      5        4   6  10  10  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
390  ...      5        5      4     4     5      4       11   9   9   9  
391  ...      2        4      5     3     4      2        3  14  16  16  
392  ...      5        5      3     3     3      3        3  10   8   7  
393  ...      4        4      1     3     4      5        0  11  12  10  
394  ...      3        2      3     3     3      5        5   8   9   9  

[395 rows x 33 columns]

In [52]:
df.head()

team       team_leader  targeted_productivity    smv    wip  over_time  \
0     9      Jane Jackson                   0.75   3.94    NaN        960   
1     7       Sarah Jones                   0.65  30.10  909.0       7080   
2     3  William Anderson                   0.80   4.15    NaN       1440   
3     1      Robert Smith                   0.65  22.53  762.0       5040   
4     4       James Jones                   0.70  30.10  767.0       3300   

   incentive  idle_time  idle_men  no_of_style_change  ...  \
0          0        0.0         0                   0  ...   
1          0        0.0         0                   1  ...   
2          0        0.0         0                   0  ...   
3          0        0.0         0                   1  ...   
4         50        0.0         0                   1  ...   

   department_finishing  department_finishing   department_sweing  day_Monday  \
0                     1                      0                  0           0   
1                     0                      0                  1           0   
2                     0                      1                  0           0   
3                     0                      0                  1           0   
4                     0                      0                  1           1   

   day_Saturday  day_Sunday  day_Thursday  day_Tuesday  day_Wednesday  \
0             0           0             0            0              1   
1             0           0             1            0              0   
2             0           0             0            0              1   
3             0           0             0            0              1   
4             0           0             0            0              0   

   actual_productivity  
0             0.755167  
1             0.535678  
2             0.820833  
3             0.581131  
4             0.790003  

[5 rows x 27 columns]

In [9]:
df.tail()

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
390  ...      5        5      4     4     5      4       11   9   9   9  
391  ...      2        4      5     3     4      2        3  14  16  16  
392  ...      5        5      3     3     3      3        3  10   8   7  
393  ...      4        4      1     3     4      5        0  11  12  10  
394  ...      3        2      3     3     3      5        5   8   9   9  

[5 rows x 33 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64 
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64 
 7   Fedu        395 non-null    int64 
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64 
 13  studytime   395 non-null    int64 
 14  failures    395 non-null    int64 
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher    

In [19]:
df.to_csv('student_data.csv')
df

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        6   5   6   6  
1    ...      5        3      3     1     1      3        4   5   5   6  
2    ...      4        3      2     2     3      3       10   7   8  10  
3    ...      3        2      2     1     1      5        2  15  14  15  
4    ...      4        3      2     1     2      5        4   6  10  10  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
390  ...      5        5      4     4     5      4       11   9   9   9  
391  ...      2        4      5     3     4      2        3  14  16  16  
392  ...      5        5      3     3     3      3        3  10   8   7  
393  ...      4        4      1     3     4      5        0  11  12  10  
394  ...      3        2      3     3     3      5        5   8   9   9  

[395 rows x 33 columns]

In [1]:
import pandas as pd

emp = pd.read_csv("employee_promotion.csv")
df=pd.DataFrame(emp)
df

Unnamed: 0  employee_id         department     region  \
0               0        65438  Sales & Marketing   region_7   
1               1        65141         Operations  region_22   
2               2         7513  Sales & Marketing  region_19   
3               3         2542  Sales & Marketing  region_23   
4               4        48945         Technology  region_26   
...           ...          ...                ...        ...   
54803       54803         3030         Technology  region_14   
54804       54804        74592         Operations  region_27   
54805       54805        13918          Analytics   region_1   
54806       54806        13614  Sales & Marketing   region_9   
54807       54807        51526                 HR  region_22   

              education gender recruitment_channel  no_of_trainings  age  \
0      Master's & above      f            sourcing                1   35   
1            Bachelor's      m               other                1   30   
2            Bachelor's      m            sourcing                1   34   
3            Bachelor's      m               other                2   39   
4            Bachelor's      m               other                1   45   
...                 ...    ...                 ...              ...  ...   
54803        Bachelor's      m            sourcing                1   48   
54804  Master's & above      f               other                1   37   
54805        Bachelor's      m               other                1   27   
54806               NaN      m            sourcing                1   29   
54807        Bachelor's      m               other                1   27   

       previous_year_rating  length_of_service  awards_won  \
0                       5.0                  8           0   
1                       5.0                  4           0   
2                       3.0                  7           0   
3                       1.0                 10           0   
4                       3.0                  2           0   
...                     ...                ...         ...   
54803                   3.0                 17           0   
54804                   2.0                  6           0   
54805                   5.0                  3           0   
54806                   1.0                  2           0   
54807                   1.0                  5           0   

       avg_training_score  is_promoted  
0                    49.0            0  
1                    60.0            0  
2                    50.0            0  
3                    50.0            0  
4                    73.0            0  
...                   ...          ...  
54803                78.0            0  
54804                56.0            0  
54805                79.0            0  
54806                 NaN            0  
54807                49.0            0  

[54808 rows x 14 columns]

In [3]:
df.head()

Unnamed: 0  employee_id         department     region         education  \
0           0        65438  Sales & Marketing   region_7  Master's & above   
1           1        65141         Operations  region_22        Bachelor's   
2           2         7513  Sales & Marketing  region_19        Bachelor's   
3           3         2542  Sales & Marketing  region_23        Bachelor's   
4           4        48945         Technology  region_26        Bachelor's   

  gender recruitment_channel  no_of_trainings  age  previous_year_rating  \
0      f            sourcing                1   35                   5.0   
1      m               other                1   30                   5.0   
2      m            sourcing                1   34                   3.0   
3      m               other                2   39                   1.0   
4      m               other                1   45                   3.0   

   length_of_service  awards_won  avg_training_score  is_promoted  
0                  8           0                49.0            0  
1                  4           0                60.0            0  
2                  7           0                50.0            0  
3                 10           0                50.0            0  
4                  2           0                73.0            0

In [5]:
df.tail()

Unnamed: 0  employee_id         department     region  \
54803       54803         3030         Technology  region_14   
54804       54804        74592         Operations  region_27   
54805       54805        13918          Analytics   region_1   
54806       54806        13614  Sales & Marketing   region_9   
54807       54807        51526                 HR  region_22   

              education gender recruitment_channel  no_of_trainings  age  \
54803        Bachelor's      m            sourcing                1   48   
54804  Master's & above      f               other                1   37   
54805        Bachelor's      m               other                1   27   
54806               NaN      m            sourcing                1   29   
54807        Bachelor's      m               other                1   27   

       previous_year_rating  length_of_service  awards_won  \
54803                   3.0                 17           0   
54804                   2.0                  6           0   
54805                   5.0                  3           0   
54806                   1.0                  2           0   
54807                   1.0                  5           0   

       avg_training_score  is_promoted  
54803                78.0            0  
54804                56.0            0  
54805                79.0            0  
54806                 NaN            0  
54807                49.0            0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54808 entries, 0 to 54807
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Unnamed: 0            54808 non-null  int64  
 1   employee_id           54808 non-null  int64  
 2   department            54808 non-null  object 
 3   region                54808 non-null  object 
 4   education             52399 non-null  object 
 5   gender                54808 non-null  object 
 6   recruitment_channel   54808 non-null  object 
 7   no_of_trainings       54808 non-null  int64  
 8   age                   54808 non-null  int64  
 9   previous_year_rating  50684 non-null  float64
 10  length_of_service     54808 non-null  int64  
 11  awards_won            54808 non-null  int64  
 12  avg_training_score    52248 non-null  float64
 13  is_promoted           54808 non-null  int64  
dtypes: float64(2), int64(7), object(5)
memory usage: 5.9+ MB


In [19]:
#groupby education or any other catergory
df = pd.read_csv("employee_promotion.csv")
empgby = df.groupby(['education']).size()
gby=pd.DataFrame(empgby)
gby

0
education              
Bachelor's        36669
Below Secondary     805
Master's & above  14925

In [21]:
#group by two columns
df = pd.read_csv("employee_promotion.csv")
empqtr = df.groupby(['department', 'education']).size()
grpqrt=pd.DataFrame(empqtr)
grpqrt

0
department        education              
Analytics         Bachelor's         3978
                  Master's & above   1037
Finance           Bachelor's         1895
                  Below Secondary     106
                  Master's & above    499
HR                Bachelor's         1525
                  Below Secondary     128
                  Master's & above    733
Legal             Bachelor's          814
                  Below Secondary      65
                  Master's & above    156
Operations        Bachelor's         7781
                  Below Secondary     176
                  Master's & above   3165
Procurement       Bachelor's         4393
                  Below Secondary     129
                  Master's & above   2544
R&D               Bachelor's          542
                  Master's & above    429
Sales & Marketing Bachelor's        11099
                  Master's & above   4166
Technology        Bachelor's         4642
                  Below Secondary     201
                  Master's & above   2196

In [27]:
df.columns

Index(['Unnamed: 0', 'employee_id', 'department', 'region', 'education',
       'gender', 'recruitment_channel', 'no_of_trainings', 'age',
       'previous_year_rating', 'length_of_service', 'awards_won',
       'avg_training_score', 'is_promoted'],
      dtype='object')

In [29]:
# Calculates the average training score for each department
df.columns = df.columns.str.strip()
avgtrain = df.groupby('department')['avg_training_score'].mean()
print(avgtrain)

department
Analytics            84.602952
Finance              60.111661
HR                   50.182482
Legal                59.716157
Operations           60.118521
Procurement          70.126279
R&D                  84.596597
Sales & Marketing    50.427416
Technology           79.928692
Name: avg_training_score, dtype: float64


In [31]:
df.to_csv('employee_promotion.csv')
df

Unnamed: 0  employee_id         department     region  \
0               0        65438  Sales & Marketing   region_7   
1               1        65141         Operations  region_22   
2               2         7513  Sales & Marketing  region_19   
3               3         2542  Sales & Marketing  region_23   
4               4        48945         Technology  region_26   
...           ...          ...                ...        ...   
54803       54803         3030         Technology  region_14   
54804       54804        74592         Operations  region_27   
54805       54805        13918          Analytics   region_1   
54806       54806        13614  Sales & Marketing   region_9   
54807       54807        51526                 HR  region_22   

              education gender recruitment_channel  no_of_trainings  age  \
0      Master's & above      f            sourcing                1   35   
1            Bachelor's      m               other                1   30   
2            Bachelor's      m            sourcing                1   34   
3            Bachelor's      m               other                2   39   
4            Bachelor's      m               other                1   45   
...                 ...    ...                 ...              ...  ...   
54803        Bachelor's      m            sourcing                1   48   
54804  Master's & above      f               other                1   37   
54805        Bachelor's      m               other                1   27   
54806               NaN      m            sourcing                1   29   
54807        Bachelor's      m               other                1   27   

       previous_year_rating  length_of_service  awards_won  \
0                       5.0                  8           0   
1                       5.0                  4           0   
2                       3.0                  7           0   
3                       1.0                 10           0   
4                       3.0                  2           0   
...                     ...                ...         ...   
54803                   3.0                 17           0   
54804                   2.0                  6           0   
54805                   5.0                  3           0   
54806                   1.0                  2           0   
54807                   1.0                  5           0   

       avg_training_score  is_promoted  
0                    49.0            0  
1                    60.0            0  
2                    50.0            0  
3                    50.0            0  
4                    73.0            0  
...                   ...          ...  
54803                78.0            0  
54804                56.0            0  
54805                79.0            0  
54806                 NaN            0  
54807                49.0            0  

[54808 rows x 14 columns]

In [33]:
high_scores = df[df['avg_training_score'] > 60]  # Filter rows where avg_training_score > 60
high_scores

Unnamed: 0  employee_id   department     region         education  \
4               4        48945   Technology  region_26        Bachelor's   
5               5        58896    Analytics   region_2        Bachelor's   
7               7        16290   Operations  region_34  Master's & above   
8               8        73202    Analytics  region_20        Bachelor's   
10             10        29934   Technology  region_23               NaN   
...           ...          ...          ...        ...               ...   
54795       54795        13477  Procurement  region_15  Master's & above   
54799       54799        68093  Procurement   region_2  Master's & above   
54801       54801        12431   Technology  region_26        Bachelor's   
54803       54803         3030   Technology  region_14        Bachelor's   
54805       54805        13918    Analytics   region_1        Bachelor's   

      gender recruitment_channel  no_of_trainings  age  previous_year_rating  \
4          m               other                1   45                   3.0   
5          m            sourcing                2   31                   3.0   
7          m            sourcing                1   33                   3.0   
8          m               other                1   28                   4.0   
10         m            sourcing                1   30                   NaN   
...      ...                 ...              ...  ...                   ...   
54795      m               other                1   35                   3.0   
54799      f               other                1   50                   5.0   
54801      f            sourcing                1   31                   NaN   
54803      m            sourcing                1   48                   3.0   
54805      m               other                1   27                   5.0   

       length_of_service  awards_won  avg_training_score  is_promoted  
4                      2           0                73.0            0  
5                      7           0                85.0            0  
7                      6           0                63.0            0  
8                      5           0                83.0            0  
10                     1           0                77.0            0  
...                  ...         ...                 ...          ...  
54795                  7           0                70.0            0  
54799                  6           1                67.0            0  
54801                  1           0                78.0            0  
54803                 17           0                78.0            0  
54805                  3           0                79.0            0  

[24906 rows x 14 columns]

In [35]:
sorted_df = df.sort_values(by='avg_training_score', ascending=False)
sorted_df

Unnamed: 0  employee_id         department     region  \
43972       43972        10940          Analytics  region_29   
47005       47005        29956  Sales & Marketing  region_22   
3261         3261        66362        Procurement   region_2   
725           725        70800         Operations   region_4   
38578       38578        52634  Sales & Marketing   region_5   
...           ...          ...                ...        ...   
54701       54701        23170  Sales & Marketing  region_28   
54736       54736        38707         Operations  region_31   
54746       54746        10546            Finance   region_6   
54773       54773        37919            Finance   region_2   
54806       54806        13614  Sales & Marketing   region_9   

              education gender recruitment_channel  no_of_trainings  age  \
43972  Master's & above      m               other                1   33   
47005        Bachelor's      m               other                1   28   
3261         Bachelor's      f               other                1   60   
725    Master's & above      f            sourcing                1   37   
38578        Bachelor's      m               other                1   48   
...                 ...    ...                 ...              ...  ...   
54701  Master's & above      m               other                1   39   
54736        Bachelor's      m               other                1   34   
54746        Bachelor's      m               other                1   28   
54773        Bachelor's      m               other                1   23   
54806               NaN      m            sourcing                1   29   

       previous_year_rating  length_of_service  awards_won  \
43972                   4.0                  9           0   
47005                   3.0                  2           0   
3261                    3.0                 21           0   
725                     5.0                  8           1   
38578                   4.0                 19           0   
...                     ...                ...         ...   
54701                   1.0                 11           0   
54736                   5.0                  6           0   
54746                   NaN                  1           0   
54773                   NaN                  1           0   
54806                   1.0                  2           0   

       avg_training_score  is_promoted  
43972                99.0            1  
47005                99.0            1  
3261                 99.0            1  
725                  99.0            1  
38578                99.0            1  
...                   ...          ...  
54701                 NaN            0  
54736                 NaN            0  
54746                 NaN            0  
54773                 NaN            0  
54806                 NaN            0  

[54808 rows x 14 columns]

In [37]:
#Aggregation 
#Combine data into meaningful summaries using functions like sum, mean, count
summary = df.groupby('department').agg({
    'avg_training_score': 'mean',
    'previous_year_rating': 'max',
    
})
summary

avg_training_score  previous_year_rating
department                                                 
Analytics                   84.602952                   5.0
Finance                     60.111661                   5.0
HR                          50.182482                   5.0
Legal                       59.716157                   5.0
Operations                  60.118521                   5.0
Procurement                 70.126279                   5.0
R&D                         84.596597                   5.0
Sales & Marketing           50.427416                   5.0
Technology                  79.928692                   5.0

In [39]:
#Pivot Tables
#Similar to Excel,it summarizes data with rows, columns, and values

#Create a pivot table to see promotions by department and gender
pivot = df.pivot_table(values='is_promoted', index='department', columns='gender', aggfunc='sum')
pivot


gender               f     m
department                  
Analytics           62   450
Finance             55   151
HR                  58    78
Legal                6    47
Operations         442   581
Procurement        385   303
R&D                  6    63
Sales & Marketing  176  1037
Technology         277   491

In [41]:
#handling Missing Data (isna(), fillna(), dropna())
#Check, clean, or replace missing values.

#Example:

#Find missing values

df.isna().sum()

Unnamed: 0                 0
employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
awards_won                 0
avg_training_score      2560
is_promoted                0
dtype: int64